### GraphQL Post allFindMembers

POST http://localhost:8080/graphql
Content-Type: application/graphql

query {
    allFindMembers {
        memberSn
        memberId
        memberEmail
        memberNumber
    }
}

### GraphQL Post registerMember

POST http://localhost:8080/graphql
Content-Type: application/graphql

mutation {
    registerMember(memberId: "test3", memberEmail: "test@test.com", memberNumber: "01012345678") {
        memberId
        memberEmail
        memberNumber
    }
}

### GraphQL Post deleteMember

POST http://localhost:8080/graphql
Content-Type: application/graphql

mutation {
    deleteMember(memberId: "test3")
}