### allMembers

POST http://localhost:8080/graphql
Content-Type: application/graphql

query {
    allMembers {
        memberSn
        memberId
        memberEmail
        memberNumber
    }
}


### queryMembers (email)

POST http://localhost:8080/graphql
Content-Type: application/graphql

query {
    queryMembers(memberDto: {memberEmail: "test@test.com"}) {
        memberId
        memberEmail
        memberNumber
    }
}

### queryMembers (number)

POST http://localhost:8080/graphql
Content-Type: application/graphql

query {
    queryMembers(memberDto: {memberNumber: "45678"}) {
        memberId
        memberEmail
        memberNumber
    }
}


### createMember

POST http://localhost:8080/graphql
Content-Type: application/graphql

mutation {
    createMember(memberId: "test3", memberEmail: "test@test.com", memberNumber: "01012345678") {
        memberId
        memberEmail
        memberNumber
    }
}

### deleteMember

POST http://localhost:8080/graphql
Content-Type: application/graphql

mutation {
    deleteMember(memberId: "test3")
}